# Generated by Django 3.2.7 on 2022-06-03 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_check', 'Проверяться'), ('closed', 'Закрыт')], max_length=50)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=5)),
                ('date_birth', models.DateField()),
                ('body', models.TextField()),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=5)),
                ('days', models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница')], max_length=5)),
                ('timeslot', models.IntegerField(choices=[(1, '09:00 – 10:00'), (2, '10:00 – 11:00'), (3, '11:00 – 12:00'), (4, '12:00 – 13:00'), (5, '13:00 – 14:00'), (6, '14:00 – 15:00'), (7, '15:00 – 16:00'), (8, '16:00 – 17:00'), (9, '17:00 – 18:00')])),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('days', 'doctor', 'timeslot')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(through='appointment.AppointmentItem', to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
