# Generated by Django 4.0.5 on 2022-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentitem',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
